# Generated by Django 4.1.3 on 2023-11-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nameCategory_en_us',
            field=models.CharField(help_text='Имя категории', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='nameCategory_ru',
            field=models.CharField(help_text='Имя категории', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='nameCategory',
            field=models.CharField(help_text='Имя категории', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en_us', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='news.category', verbose_name='This is the help text')),
            ],
        ),
    ]
