# Generated by Django 4.1.3 on 2023-12-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCreate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Respon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='Контент')),
                ('timeR', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False, verbose_name='Принять')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('postR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.post', verbose_name='Объявление')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryPC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.category')),
                ('postPC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categoryP',
            field=models.ManyToManyField(through='bulletin.PostCategory', to='bulletin.category', verbose_name='Категория'),
        ),
    ]
